version: 0.2

phases:
  pre_build:
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
    #   - python3 application.py 
artifacts:
  files:
    - '**/*'
#   base-directory: my-api